[package]
name = "tinywasm_mapper"
version = "0.1.0"
edition = "2021"
build = "../../build_user.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["dylib"]

[dependencies]
ms_std = { path = "../../ms_std", features = [
    "alloc_def",
    "unwinding",
], optional = true }
ms_hostcall = { path = "../../ms_hostcall", optional = true }

cfg-if = "1.0.0"
tinywasm = { path = "../../tinywasm", default-features = false, features = [
    "parser",
] }
unwinding = { version = "=0.2.0", features = ["panic-handler", "personality"] }
# wat = { version = "=1.0.88" }


[features]
with_libos = ["ms_std", "ms_hostcall"]
measure_mem = ["with_libos"]

default = ["with_libos"]
